const express = require('express');
const router = express.Router();
const registerController = require('./registerController.cjs');
const loginController = require('./loginController.cjs');
const postController = require('./postController.cjs');
const filterController = require('./filterController.cjs');
const searchController = require('./searchController.cjs');
const commentController = require('./commentController.cjs');
const reportController = require('./reportController.cjs');
const updateController = require('./updateController.cjs');
const adminController = require('./adminController.cjs');

router.post('/register', registerController.registerAccount);
router.post('/verify-username', registerController.verifyUsername);
router.post('/verify-login', loginController.verifyLogin);
router.post('/create-post', postController.createPost);
router.post('/delete-post', postController.deletePost);
router.post('/hide-post', postController.hidePost);
router.post('/get-post', postController.getPost);
router.post('/update-post', postController.updatePost);
router.post('/filter-post', filterController.filterPost);
router.post('/comment', commentController.createComment);
router.post('/get-comment', commentController.getComment);
router.post('/search', searchController.searchRelevantName);
router.post('/update-info', updateController.updateInfo);
router.post('/get-info', updateController.getInfo);
router.post('/get-password', updateController.getOldPassword);
router.post('/update-password', updateController.updatePassword);
router.post('/report', reportController.report);
router.post('/get-report-post', reportController.fetchPostReport);
router.post('/get-report-feedback', reportController.fetchFeedbackReport);
router.post('/remove-post', adminController.removePost);
router.post('/remove-feedback', adminController.removeFeedback);
router.post('/remove-user', adminController.removeUser);
router.post('/ignore', adminController.ignore);

module.exports = router;